### PR TITLE
Optional: add random status option

### PR DESCRIPTION
**Pull request by PH-KDX**
This sets the status message to one of several random options. Not sure about this one, but could be nice. Leaving it up to you.

### CODE REVIEW

**Review by nicolas377 — CHANGES_REQUESTED** [review]
You need to add the statuses to modules/saveJSON.js

**Comment by PH-KDX** [comment]
Surely the bot is only reading statuses, not creating them?

**Comment by nicolas377** [comment]
The bot will overwrite the json file when codes for elections are created, timezones are added, events are added, or images are added. If the codes aren't saved, they'll disappear from the json file.

**Comment by PH-KDX** [comment]
aaaarrggghhhhhh
ok, I'll do it now

**Review by nicolas377 — APPROVED** [review]

**Pull request merged**
